#!/usr/bin/env npx tsx
/**
 * Map Elite Characters to Voice Archetypes
 * 
 * This script creates a mapping between the 29 Elite Characters and
 * the ElevenLabs voice archetypes, then generates the final
 * comprehensiveVoiceMapping entries using Fish Audio clone IDs.
 * 
 * Usage: npx tsx scripts/map-elite-characters.ts
 */

import { writeFile, readFile } from 'fs/promises';
import { existsSync } from 'fs';
import path from 'path';

// Elite Character → Archetype mapping
// Based on character personality and voice seed name
const ELITE_CHARACTER_ARCHETYPES: Record<string, string> = {
    // Authority Characters
    'the-narrator': 'dark_narrator',           // Movetrailer → cinematic, commanding
    'sergeant-stone': 'gruff_enforcer',        // VeterenSoldier → military, tough
    'velvet-noir': 'seductive_temptress',      // FemmeFatale → mysterious, alluring
    'dame-victoria-sterling': 'sharp_female_intellectual', // Headmistress → British, authoritative
    'lord-pemberton': 'cynical_realist',       // Snob → aristocratic, condescending
    'mr-zero': 'cold_strategic_authority',     // Villain → cold, calculating

    // Mentor Characters
    'grandfather-oak': 'gentle_elder',         // WiseSage → wise, grandfatherly
    'dr-grace-chen': 'warm_mentor',            // Healer → empathetic, caring
    'dr-alan-marcus': 'dry_technical_explainer', // Professor → academic, precise
    'master-kai': 'serene_mystic',             // Meditative → calm, zen
    'nana-rose': 'warm_female_guide',          // Grandma → motherly, warm

    // Energetic Characters
    'jake-blitz': 'high_energy_motivator',     // Youtuber → loud, excited
    'sunny-day': 'cheerful_optimist',          // Bubbly → positive, bright
    'danny-swift': 'charismatic_rogue',        // Cockney → street-smart, charming
    'raven-black': 'fierce_rebel',             // Raspy → punk, cynical
    'coach-thunder': 'high_energy_motivator',  // Coach → loud, motivational

    // Texture Characters  
    'the-whisper': 'serene_mystic',            // Intimate → soft, ASMR
    'dr-calm': 'serene_mystic',                // Male ASMR → extremely calm
    'aria-7': 'cold_strategic_authority',      // Etheral → AI, otherworldly
    'nigel-wimple': 'anxious_neurotic',        // Coward → nervous, stammering
    'milton-specs': 'shy_reserved_thinker',    // Nasal → nerdy, technical
    'madison-star': 'youthful_curious_voice',  // Valley → Gen-Z, influencer

    // Global Characters
    'max-outback': 'fast_talking_operator',    // Australian → laid-back Aussie
    'amelie-laurent': 'seductive_temptress',   // French → romantic French
    'raj-sharma': 'fast_talking_operator',     // Indian → energetic entrepreneur
    'ingrid-frost': 'calm_female_authority',   // Scandanavian → cool Nordic
    'coach-kofi': 'high_energy_motivator',     // WestAfrican → powerful mentor
    'thabo-wilde': 'noble_commander',          // SouthAfrican → rhythmic guide
    'smooth-johnny': 'smooth_persuader',       // AfricanAmerican → jazz, soulful
};

async function main() {
    console.log('🎭 Elite Character → Archetype Mapper\n');

    // Check if Fish Audio clone IDs exist
    const cloneIdsPath = path.join(process.cwd(), 'lib', 'audio', 'fishAudioCloneIds.ts');

    if (!existsSync(cloneIdsPath)) {
        console.log('⚠️  Fish Audio clone IDs not found.');
        console.log('   Run these scripts first:');
        console.log('   1. npx tsx scripts/download-elevenlabs-samples.ts');
        console.log('   2. npx tsx scripts/clone-to-fish-audio.ts');
        console.log('\n   For now, generating archetype mapping only...\n');
    }

    // Generate the mapping file
    const mappingContent = `/**
 * Elite Character Voice Mapping
 * 
 * Maps the 29 Elite Characters to their Fish Audio clone IDs.
 * These clones were created from ElevenLabs voice samples.
 * 
 * Generated: ${new Date().toISOString()}
 */

// Import Fish Audio clone IDs (generated by clone-to-fish-audio.ts)
// import { FISH_AUDIO_CLONE_IDS } from './fishAudioCloneIds';

// Character → Archetype mapping
export const ELITE_CHARACTER_ARCHETYPES: Record<string, string> = {
${Object.entries(ELITE_CHARACTER_ARCHETYPES)
            .map(([char, arch]) => `    '${char}': '${arch}',`)
            .join('\n')}
};

// Function to get Fish Audio voice ID for an Elite Character
export function getEliteCharacterVoice(characterSeedId: string): string | null {
    const archetype = ELITE_CHARACTER_ARCHETYPES[characterSeedId];
    if (!archetype) {
        console.warn(\`[Voice] No archetype mapping for character: \${characterSeedId}\`);
        return null;
    }
    
    // TODO: Once Fish Audio clone IDs are generated, uncomment:
    // const voiceId = FISH_AUDIO_CLONE_IDS[archetype];
    // if (voiceId) return voiceId;
    
    console.warn(\`[Voice] No Fish Audio clone ID for archetype: \${archetype}\`);
    return null;
}
`;

    const outputPath = path.join(process.cwd(), 'lib', 'audio', 'eliteCharacterVoices.ts');
    await writeFile(outputPath, mappingContent);

    console.log(`✅ Generated: ${outputPath}`);
    console.log(`   Mapped ${Object.keys(ELITE_CHARACTER_ARCHETYPES).length} characters`);

    // Print mapping table
    console.log('\n📊 Character → Archetype Mapping:\n');
    console.log('| Character | Archetype |');
    console.log('|-----------|-----------|');
    for (const [char, arch] of Object.entries(ELITE_CHARACTER_ARCHETYPES)) {
        console.log(`| ${char} | ${arch} |`);
    }
}

main().catch(console.error);
